version: '3.9'

services:
  laravel:
    build:
      context: .
      dockerfile: Laravel.Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      APP_ENV: 'local'
      APP_DEBUG: '1'
      APP_KEY: 'base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX='
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'intelliform'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      PHP_SERVICE_NAME: 'laravel'
      PHP_SERVICE_PORT: '8000'
    depends_on:
      - db
    ports:
      - '3000:3000'
      - '8000:8000'
      - '8080:8080'
      - '9000:9000'
    networks:
      - intelliform

  db:
    image: postgres:13.10
    container_name: postgres_db
    environment:
      - POSTGRES_DB=intelliform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - intelliform

volumes:
  pgdata:

networks:
  intelliform:
    driver: bridge
